#!/bin/bash
#SBATCH --job-name=flush        ### Job Name
#SBATCH --output=flush.out      ### File in which to store job output
#SBATCH --error=flush.err       ### File in which to store job error messages
#SBATCH --qos=long              ### Quality of Service
#SBATCH --time=7-00:00:00       ### Wall clock time limit in Days-HH:MM:SS
#SBATCH --nodes=1               ### Node count required for the job
#SBATCH --ntasks-per-node=1

#../flush.exe

module load gcc
module load intel-psxe
module load eigen
make
./flush.exe
#icpc -std=c++11 -openmp -I ~/Eigen/Eigen -I ~/Eigen/unsupported/Eigen ../flush_main.cpp ../basic_funcs.cpp
#./a.out
